{
 "title": "Geocitizen monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Tomcat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.tomcat.cpu-0.cpu-system"
    },
    {
     "target": "collectd.tomcat.cpu-1.cpu-system"
    }
   ]
  },
  {
   "title": "Memory Tomcat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.tomcat.memory.memory-used"
    }
   ]
  },
  {
   "title": "CPU Postgres",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.postgres.cpu-0.cpu-system"
    },
    {
     "target": "collectd.postgres.cpu-1.cpu-system"
    }
   ]
  },
  {
   "title": "Memory Postgres",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.postgres.memory.memory-used"
    }
   ]
  },
  {
   "title": "CPU Jenkins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.jenkins.cpu-0.cpu-system"
    },
    {
     "target": "collectd.jenkins.cpu-1.cpu-system"
    }
   ]
  },
  {
   "title": "Memory Jenkins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.jenkins.memory.memory-used"
    }
   ]
  },
  {
   "title": "CPU Graphite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.graphite.cpu-0.cpu-system"
    },
    {
     "target": "collectd.graphite.cpu-1.cpu-system"
    }
   ]
  },
  {
   "title": "Memory Graphite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.graphite.memory.memory-used"
    }
   ]
  },
  {
   "title": "CPU AWX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.awx.cpu-0.cpu-system" },
    { "target": "collectd.awx.cpu-1.cpu-system" }
   ]
  },
  {
   "title": "Memory AWX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.awx.memory.memory-used"
    }
   ]
  }
 ]
}